# Global settings applied to the whole site.
[build]
  publish = "public"

# CORS Headers
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://qr-code-web-app-wu0o.onrender.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"